package Exceptions;

public class OtherExceptions extends Exception{
	
	public final static String NOT_GOOD_SIZE = "ERREUR SAISIE DE TAILLE \nPOUR RAPPEL LA TAILLE MINIMAL EST DE 20 ET LA TAILLE MAXIMALE EST DE 70";
	public final static String NOT_DRAGGABLE = "LE MUR EST EN DEHORS DU PLATEAU ";
	public final static String WRONG_VALUES = "LES VALEURS CHOISIS EXCEDENT LE PLATEAU DE JEU, VOUS N'AVEZ PAS LE DROIT D'ALLER EN DESSOUS DE 0 OU PLUS QUE LE MAXIMUM DE LA TAILLE DU PLATEAU ";
}